# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'storemart_vendor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'IQKeyboardManagerSwift'
pod 'Charts'
pod 'MBProgressHUD'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'SDWebImage'

  # Pods for storemart_vendor

end
