# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nectar Grocery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'Firebase'
pod ‘Firebase/Database’
pod 'FirebaseAuth'
pod 'FirebaseCore'
pod 'IQKeyboardManagerSwift'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

pod 'GoogleSignIn'

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SDWebImage'
pod 'iOSDropDown'


  # Pods for Nectar Grocery

end
