# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FashionHub_User' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'IQKeyboardManagerSwift'
pod 'MBProgressHUD'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'SDWebImage'


  # Pods for FashionHub_User

end
