# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'imageDisplay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for imageDisplay

pod 'Alamofire', '~> 5.2'
pod 'ReachabilitySwift', '~> 3'
pod 'SDWebImage'

  target 'imageDisplayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'imageDisplayUITests' do
    # Pods for testing
  end

end
